command: sudo puppet agent -tv
codes:
  ok: [ 0,2 ]
  warning: [ 1,3,4,5,6 ]

args:
  - domain

params:
  num: [ 1,2 ]

aliases:
  fe: [ web, api ]

servers:
  web: web{{.num}}.{{.domain}}.pp
  api: api{{.num}}.{{.domain}}.pp
  cron: cron.{{.domain}}.pp
  worker:
    mask: worker{{.num}}.{{.domain}}.pp
    params:
      num: [ 1 ]
